services:
  # --- 1. CONFIGURACIÓN DEL SERVIDOR DESDE DOCKERFILE ---
  postgres_server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: psql_server
    ports:
      - "5432:5432"
    networks:
      - red_taller

  # --- 2. CONFIGURACIÓN DEL CLIENTE DESDE DOCKERFILE ---
  postgres_client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: psql_client
    stdin_open: true
    tty: true
    networks:
      - red_taller
    depends_on:
      - postgres_server

  # --- 3. CONTENEDOR DE CAPTURA AUTOMÁTICA (PCAP) ---
  captura_trafico:
    image: nicolaka/netshoot
    container_name: psql_capture
    network_mode: "service:postgres_server"
    volumes:
      - ./:/data
    command: tcpdump -i any port 5432 -w /data/captura_postgres.pcap
    depends_on:
      - postgres_server

networks:
  red_taller:
    driver: bridge